name: postgresql-flyway-migrations
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ secrets.DB_D }}
          POSTGRES_USER: ${{ secrets.DB_U }}
          POSTGRES_PASSWORD: ${{ secrets.KUNLE_BABA }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: ${{ secrets.DB_URI }}
          user: ${{ secrets.DB_U }}
          password: ${{ secrets.KUNLE_BABA }}
          locations: filesystem:./sql
      - run: echo 'testing'


  deploy-to-prod:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: ${{ secrets.DB_URI }}
          user: ${{ secrets.DB_U }}
          password: ${{ secrets.KUNLE_BABA }}
          locations: filesystem:./sql
      - run: echo 'deploying to prod'
